services:
  app:
    image: sao-blog-server:latest
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3090:3000"
    env_file: apps/server/.env
    restart: unless-stopped
    networks:
      - pg-network
      
networks:
  pg-network:
    external: true