/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LayoutNotesRouteRouteImport } from './routes/_layout/notes/route'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayouthomeIndexRouteImport } from './routes/_layout/(home)/index'
import { Route as LayoutCategoriesSlugRouteImport } from './routes/_layout/categories/$slug'
import { Route as LayoutNotesIndexRouteImport } from './routes/_layout/notes/index'
import { Route as LayoutNotesIdRouteImport } from './routes/_layout/notes/$id'
import { Route as LayoutPostsIndexRouteImport } from './routes/_layout/posts/index'
import { Route as LayoutPostsSlugRouteImport } from './routes/_layout/posts/$slug'
import { Route as LayoutThinkingIndexRouteImport } from './routes/_layout/thinking/index'
import { Route as LayoutTimelineIndexRouteImport } from './routes/_layout/timeline/index'
import { Route as LayoutNotesTopicsIndexRouteImport } from './routes/_layout/notes/topics/index'
import { Route as LayoutNotesTopicsSlugRouteImport } from './routes/_layout/notes/topics/$slug'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutNotesRouteRoute = LayoutNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayouthomeIndexRoute = LayouthomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCategoriesSlugRoute = LayoutCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutNotesIndexRoute = LayoutNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutNotesRouteRoute,
} as any)
const LayoutNotesIdRoute = LayoutNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutNotesRouteRoute,
} as any)
const LayoutPostsIndexRoute = LayoutPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPostsSlugRoute = LayoutPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutThinkingIndexRoute = LayoutThinkingIndexRouteImport.update({
  id: '/thinking/',
  path: '/thinking/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutTimelineIndexRoute = LayoutTimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutNotesTopicsIndexRoute = LayoutNotesTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => LayoutNotesRouteRoute,
} as any)
const LayoutNotesTopicsSlugRoute = LayoutNotesTopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => LayoutNotesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayouthomeIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/notes': typeof LayoutNotesRouteRouteWithChildren
  '/api/revalidate': typeof ApiRevalidateRoute
  '/login/': typeof LoginIndexRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/notes/$id': typeof LayoutNotesIdRoute
  '/posts/$slug': typeof LayoutPostsSlugRoute
  '/notes/': typeof LayoutNotesIndexRoute
  '/posts/': typeof LayoutPostsIndexRoute
  '/thinking/': typeof LayoutThinkingIndexRoute
  '/timeline/': typeof LayoutTimelineIndexRoute
  '/notes/topics/$slug': typeof LayoutNotesTopicsSlugRoute
  '/notes/topics/': typeof LayoutNotesTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/login': typeof LoginIndexRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/notes/$id': typeof LayoutNotesIdRoute
  '/posts/$slug': typeof LayoutPostsSlugRoute
  '/': typeof LayouthomeIndexRoute
  '/notes': typeof LayoutNotesIndexRoute
  '/posts': typeof LayoutPostsIndexRoute
  '/thinking': typeof LayoutThinkingIndexRoute
  '/timeline': typeof LayoutTimelineIndexRoute
  '/notes/topics/$slug': typeof LayoutNotesTopicsSlugRoute
  '/notes/topics': typeof LayoutNotesTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_layout/notes': typeof LayoutNotesRouteRouteWithChildren
  '/api/revalidate': typeof ApiRevalidateRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/_layout/notes/$id': typeof LayoutNotesIdRoute
  '/_layout/posts/$slug': typeof LayoutPostsSlugRoute
  '/_layout/(home)/': typeof LayouthomeIndexRoute
  '/_layout/notes/': typeof LayoutNotesIndexRoute
  '/_layout/posts/': typeof LayoutPostsIndexRoute
  '/_layout/thinking/': typeof LayoutThinkingIndexRoute
  '/_layout/timeline/': typeof LayoutTimelineIndexRoute
  '/_layout/notes/topics/$slug': typeof LayoutNotesTopicsSlugRoute
  '/_layout/notes/topics/': typeof LayoutNotesTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/notes'
    | '/api/revalidate'
    | '/login/'
    | '/categories/$slug'
    | '/notes/$id'
    | '/posts/$slug'
    | '/notes/'
    | '/posts/'
    | '/thinking/'
    | '/timeline/'
    | '/notes/topics/$slug'
    | '/notes/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/revalidate'
    | '/login'
    | '/categories/$slug'
    | '/notes/$id'
    | '/posts/$slug'
    | '/'
    | '/notes'
    | '/posts'
    | '/thinking'
    | '/timeline'
    | '/notes/topics/$slug'
    | '/notes/topics'
  id:
    | '__root__'
    | '/_layout'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/_layout/notes'
    | '/api/revalidate'
    | '/login/'
    | '/_layout/categories/$slug'
    | '/_layout/notes/$id'
    | '/_layout/posts/$slug'
    | '/_layout/(home)/'
    | '/_layout/notes/'
    | '/_layout/posts/'
    | '/_layout/thinking/'
    | '/_layout/timeline/'
    | '/_layout/notes/topics/$slug'
    | '/_layout/notes/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/notes': {
      id: '/_layout/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof LayoutNotesRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/(home)/': {
      id: '/_layout/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayouthomeIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/categories/$slug': {
      id: '/_layout/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof LayoutCategoriesSlugRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/notes/': {
      id: '/_layout/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof LayoutNotesIndexRouteImport
      parentRoute: typeof LayoutNotesRouteRoute
    }
    '/_layout/notes/$id': {
      id: '/_layout/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof LayoutNotesIdRouteImport
      parentRoute: typeof LayoutNotesRouteRoute
    }
    '/_layout/posts/': {
      id: '/_layout/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof LayoutPostsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/posts/$slug': {
      id: '/_layout/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof LayoutPostsSlugRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/thinking/': {
      id: '/_layout/thinking/'
      path: '/thinking'
      fullPath: '/thinking/'
      preLoaderRoute: typeof LayoutThinkingIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/timeline/': {
      id: '/_layout/timeline/'
      path: '/timeline'
      fullPath: '/timeline/'
      preLoaderRoute: typeof LayoutTimelineIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/notes/topics/': {
      id: '/_layout/notes/topics/'
      path: '/topics'
      fullPath: '/notes/topics/'
      preLoaderRoute: typeof LayoutNotesTopicsIndexRouteImport
      parentRoute: typeof LayoutNotesRouteRoute
    }
    '/_layout/notes/topics/$slug': {
      id: '/_layout/notes/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/notes/topics/$slug'
      preLoaderRoute: typeof LayoutNotesTopicsSlugRouteImport
      parentRoute: typeof LayoutNotesRouteRoute
    }
  }
}

interface LayoutNotesRouteRouteChildren {
  LayoutNotesIdRoute: typeof LayoutNotesIdRoute
  LayoutNotesIndexRoute: typeof LayoutNotesIndexRoute
  LayoutNotesTopicsSlugRoute: typeof LayoutNotesTopicsSlugRoute
  LayoutNotesTopicsIndexRoute: typeof LayoutNotesTopicsIndexRoute
}

const LayoutNotesRouteRouteChildren: LayoutNotesRouteRouteChildren = {
  LayoutNotesIdRoute: LayoutNotesIdRoute,
  LayoutNotesIndexRoute: LayoutNotesIndexRoute,
  LayoutNotesTopicsSlugRoute: LayoutNotesTopicsSlugRoute,
  LayoutNotesTopicsIndexRoute: LayoutNotesTopicsIndexRoute,
}

const LayoutNotesRouteRouteWithChildren =
  LayoutNotesRouteRoute._addFileChildren(LayoutNotesRouteRouteChildren)

interface LayoutRouteRouteChildren {
  LayoutNotesRouteRoute: typeof LayoutNotesRouteRouteWithChildren
  LayoutCategoriesSlugRoute: typeof LayoutCategoriesSlugRoute
  LayoutPostsSlugRoute: typeof LayoutPostsSlugRoute
  LayouthomeIndexRoute: typeof LayouthomeIndexRoute
  LayoutPostsIndexRoute: typeof LayoutPostsIndexRoute
  LayoutThinkingIndexRoute: typeof LayoutThinkingIndexRoute
  LayoutTimelineIndexRoute: typeof LayoutTimelineIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutNotesRouteRoute: LayoutNotesRouteRouteWithChildren,
  LayoutCategoriesSlugRoute: LayoutCategoriesSlugRoute,
  LayoutPostsSlugRoute: LayoutPostsSlugRoute,
  LayouthomeIndexRoute: LayouthomeIndexRoute,
  LayoutPostsIndexRoute: LayoutPostsIndexRoute,
  LayoutThinkingIndexRoute: LayoutThinkingIndexRoute,
  LayoutTimelineIndexRoute: LayoutTimelineIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
